nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.3.cjs

npmScopes:
  chrisofnormandy:
    npmRegistryServer: "https://npm.pkg.github.com"

npmRegistries: 
    "https://npm.pkg.github.com": 
        npmAuthToken: "${GITHUB_TOKEN}"